name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    # REVISION DE CÓDIGO
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    # CONFIGURACIÖN DE SEMANTIC 
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with: 
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
    
    # CONEXION CON DOCKER LOGIN
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    # CONSTRUIR LA IMAGEN DE DOCKER
    - name: Build Docker Image
      env: 
        NEW_VERSION: ${{ steps.version.outputs.version }}

      run : |
        docker build -t getsemani/docker-graphql:$NEW_VERSION .
        docker build -t getsemani/docker-graphql:latest .

    # PUBLICAR LA IMAGEN DE DOCKER
    - name: Push Docker Image
      env: 
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run : |
        docker push getsemani/docker-graphql:$NEW_VERSION
        docker push getsemani/docker-graphql:latest
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
